---
- name: "Download Ops Manager RPM"
  get_url:
    url: "{{om_download_url36}}"
    dest: /tmp/mongodb-mms.rpm
    force_basic_auth: yes
- name: "Install the RPM"
  yum:
    name: /tmp/mongodb-mms.rpm
    state: present
- name: "Enable mongodb-mms service"
  service:
    name: mongodb-mms
    enabled: yes
- name: "Copy configuration files"
  template: 
    src="../files/conf-mms.properties"
    dest="/opt/mongodb/mms/conf/conf-mms.properties"
    owner=root 
    group=root 
    mode="u=rw,g=r,o=r"
- name: "Start mongodb-mms service"
  service: name=mongodb-mms state=started
  become: yes
- name: "Create initial user"
  uri:
    url: "http://192.168.1.100:8080/api/public/v1.0/unauth/users"
    method: POST
    validate_certs: no
    follow_redirects: all
    headers:
      Content-Type: "application/json"
    body_format: json
    status_code: 201
    body: "{{first_user_api_call}}"
    return_content: yes
    register: api_key
- name: "Printing result"
  debug:
    msg: api_key.apiKey